### ISSUE TITLE
Numerous dependencies missing

### ISSUE THREAD

**Issue by Tadasu85** [feruzm/esteem-desktop#8]
electron needs to be globally declared in npm as well as angular and some others I have not found yet. I will look into noting these more clearly in a PR

**Comment by feruzm** [comment]
Could you please clarify which ones?

When you follow Readme, do you get any issues or missing packages errors?

**Comment by Tadasu85** [comment]
Yea running npm start after installing gives this output in the JS console : 

Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/tad/esteem-desktop/scripts/lib/textAngular/dist/textAngular-rangy.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/tad/esteem-desktop/scripts/lib/textAngular/dist/textAngular-sanitize.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/tad/esteem-desktop/scripts/lib/textAngular/dist/textAngularSetup.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///home/tad/esteem-desktop/scripts/lib/textAngular/dist/textAngular.js Failed to load resource: net::ERR_FILE_NOT_FOUND
/home/tad/esteem-desktop/node_modules/angular/angular.js:32822 WARNING: Tried to load angular more than once.
module.js:457 Uncaught Error: Cannot find module 'steem-rpc'
ionic.js:17922 Uncaught Error: [$injector:modulerr] Failed to instantiate module steem due to:
Error: [$injector:modulerr] Failed to instantiate module ion-floating-menu due to:
Error: [$injector:nomod] Module 'ion-floating-menu' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.3/$injector/nomod?p0=ion-floating-menu
    at file:///home/tad/esteem-desktop/scripts/lib/ionic.js:13443:12
    at file:///home/tad/esteem-desktop/scripts/lib/ionic.js:15409:17
    at ensure (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:15333:38)
    at module (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:15407:14)
    at file:///home/tad/esteem-desktop/scripts/lib/ionic.js:17899:22
    at forEach (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:13696:20)
    at loadModules (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:17883:5)
    at file:///home/tad/esteem-desktop/scripts/lib/ionic.js:17900:40
    at forEach (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:13696:20)
    at loadModules (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:17883:5)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=ion-floating-menu&p…2F%2F%2Fhome%2Ftad%2Festeem-desktop%2Fscripts%2Flib%2Fionic.js%3A17883%3A5)
    at file:///home/tad/esteem-desktop/scripts/lib/ionic.js:13443:12
    at file:///home/tad/esteem-desktop/scripts/lib/ionic.js:17922:15
    at forEach (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:13696:20)
    at loadModules (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:17883:5)
    at file:///home/tad/esteem-desktop/scripts/lib/ionic.js:17900:40
    at forEach (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:13696:20)
    at loadModules (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:17883:5)
    at createInjector (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:17805:19)
    at doBootstrap (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:15085:20)
    at bootstrap (file:///home/tad/esteem-desktop/scripts/lib/ionic.js:15106:12)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=steem&p1=Error%3A%2…F%2F%2Fhome%2Ftad%2Festeem-desktop%2Fscripts%2Flib%2Fionic.js%3A15106%3A12)

**Comment by feruzm** [comment]
Quick fix should be available. Please view 268a38954c6b68d5fb68b94dca249b5f0e4d7cb9 and eb0f8830f533e6f30b6a6eef318c6314c0079696

Let me know if you find any more issues.

**Comment by Tadasu85** [comment]
Aha my mistake thanks man!

**Comment by Tadasu85** [comment]
alright so those suggestion didnt fix me up but here is what did:
I obtained a copy of ion-floating-menu and put it into its folder in lib/ion-floating-menu/dist
and did the same with ngcordova into lib/ngcordova/dist it seems these two packages are required but never explicitly installed.
